services:
    _defaults:
        autoconfigure: true
        autowire: false
        public: false

    Terminal42\AutoRegistrationBundle\EventListener\RegistrationListener:
        arguments:
            - '@contao.security.frontend_user_provider'
            - '@security.token_storage'
            - '@database_connection'
            - '@logger'
            - '@event_dispatcher'
            - '@request_stack'
            - '@contao.security.user_checker'
            - '@contao.security.authentication_success_handler'
        tags:
            - { name: 'monolog.logger', channel: 'terminal42_autoregistration' }
